### ISSUE TITLE
Fullscreen Apps Issue

### ISSUE THREAD

**Issue by Trintatronix** [Futur3Sn0w/maccard#13] opened 2023-05-19 21:40 UTC
When in taskbar mode, the taskbar doesn't go away if you full screen an app.

**Comment by Futur3Sn0w** [comment] 2023-05-23 00:17
This is the intended behavior, so i'm going to close this. However, a switch will be coming soon to show or hide the taskbar in fullscreen apps.

**Closed as completed by Futur3Sn0w** 2023-05-23 00:17 UTC
